### ISSUE TITLE
Possible to access/query sub-tries? 

### ISSUE THREAD

**Issue by vassudanagunta** [tchap/go-patricia#30]
I'm making use of go-patricia in a proposed new version of [Hugo](https://github.com/gohugoio/hugo). I noticed that the Trie structure is recursive, but that fact isn't exposed to the public API. For example it would be powerful to be able to query a sub-Trie in the say way you can query the root Trie. 

I don't have the time to deep dive into go-patricia's implementation, so I was hoping you could answer this for me: *Is there any technical reason why sub-Trie's can't be exposed publically? Is there something about the implementation (e.g. the way the prefixes are represented) that requires all queries to be made from the root?*

**Comment by tchap** [comment]
I will have to check in more details. The thing is, when you delete from a trie, compaction can be triggered, changing the internal data structure quite a lot, so taking a subtree would probably have to copy the whole subtree and return it as a reference. But in case that would be handy, it shouldn't be that difficult to be added. Adding the somehow dangerous version of returning the internal subtree, which is stored as a `Trie` recursively indeed, would be pretty trivial.

**Comment by tchap** [comment]
There is actually one more thing. When querying for a prefix, you don't always hit a node you could say. Every node in a trie holds particular prefix, not just a single character. Let's say you insert `aba`, `abb`, `abc`, then the root node would be associated with `ab`. Querying for `a` prefix would have to return the root node saying that `b` from the root node was actually not processed...

This is basically what I am doing here:

https://github.com/tchap/go-patricia/blob/master/patricia/patricia.go#L165

And, actually, what this issue is about is really exporting `findSubtree` method...

**Comment by tchap** [comment]
@vassudanagunta Sorry for not attending to this issue, will take a look today.

**Comment by tchap** [comment]
Added `Clone` method, then found out that the structure is not actually as recursive as I thought. You can get a subtree and insert in a way that breaks the whole trie, so I am not implementing this for now. In case someone makes a strong case for this, you can re-open and we can discuss it again...

But at least `Clone` is available now 😄
